# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate a standalone PipeWire config that runs one EQ filter-chain.

Each config runs as its own `pipewire -c <file>` process, so an EQ sink
exists exactly as long as the daemon keeps that process alive.
"""

from __future__ import annotations

import json
import re

from .apo import Preset

NODE_PREFIX = "pweq."


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "output"


def sink_name(key: str) -> str:
    return NODE_PREFIX + key


def _str(s: str) -> str:
    return json.dumps(s)  # SPA-JSON accepts JSON strings


def _num(x: float) -> str:
    return repr(float(x))


def render(key: str, target: str, description: str, preset_name: str, preset: Preset) -> str:
    nodes = [
        "{ type = builtin name = preamp label = linear "
        f'control = {{ "Mult" = {_num(10 ** (preset.preamp / 20))} "Add" = 0.0 }} }}'
    ]
    names = ["preamp"]
    for i, band in enumerate(preset.active_bands, 1):
        name = f"band{i}"
        nodes.append(
            f"{{ type = builtin name = {name} label = {band.label} "
            f'control = {{ "Freq" = {_num(band.freq)} "Q" = {_num(band.q)} "Gain" = {_num(band.gain)} }} }}'
        )
        names.append(name)
    links = [f'{{ output = "{a}:Out" input = "{b}:In" }}' for a, b in zip(names, names[1:], strict=False)]
    indent = "\n" + " " * 20
    label = f"{description} (EQ: {preset_name})"
    return f"""\
# Generated by pweq; overwritten on every change.
context.properties = {{ log.level = 0 }}
context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}}
context.modules = [
    {{ name = libpipewire-module-rt args = {{ }} flags = [ ifexists nofail ] }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}
    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = {_str(label)}
            media.name = {_str(label)}
            filter.graph = {{
                nodes = [{indent}{indent.join(nodes)}
                ]
                links = [{indent}{indent.join(links)}
                ]
            }}
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {{
                node.name = {_str(sink_name(key))}
                media.class = Audio/Sink
                priority.session = 0
            }}
            playback.props = {{
                node.name = {_str(sink_name(key) + ".out")}
                node.passive = true
                node.dont-reconnect = true
                # Pin to the real output; stops EasyEffects & co. from re-routing
                # it back into an EQ sink (feedback loop).
                node.dont-move = true
                target.object = {_str(target)}
            }}
        }}
    }}
]
"""
